language: julia

os:
  - linux

julia:
  - 1.0
  - 1
  - nightly

notifications:
  email:
    on_success: never
    on_failure: change

jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
