language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0

matrix:
  fast_finish: true

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder(), flags="julia_$(VERSION.major)_$(VERSION.minor)")'
  - julia -e 'using Pkg; Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))'
