site_name: Bootstrap.jl

site_description: Bootstrapping statistic framework for the Julia programming language

repo_name: 'juliangehring/Bootstrap.jl'
repo_url: 'https://github.com/juliangehring/Bootstrap.jl'

pages:
- Bootstrap.jl: 'index.md'
- Library: 'library.md'
- References: 'references.md'
- News: 'NEWS.md'
- License: 'LICENSE.md'

docs_dir: 'build'

site_favicon: null

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'
  social:
    - type: 'github'
      link: 'https://github.com/juliangehring'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
